### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by JeeyM** [Holfz/de2fa#1]
It's say the steam guard already disabled, but is not disabled

**Comment by Holfz** [comment]
Please try a [2.0.0 version](https://github.com/Holfz/de2fa/releases/tag/v2.0.0) and reopen issues again if you got a problem..

**Comment by Holfz** [comment]
if you got problem when using wrong user:password please try a [2.0.1 version](https://github.com/Holfz/de2fa/releases/tag/v2.0.1)
