### ISSUE TITLE
Suggestion: remove accounts from accounts.txt after disabling Steam Guard

### ISSUE THREAD

**Issue by beralbdom** [Holfz/de2fa#2]
Since it gets a timeout sometimes when waiting for the email and we have to run the script again, it would be better if the script removed accs from the account list after disabling Steam Guard on them so we don't have to login to these accounts when running the script again

**Comment by Holfz** [comment]
As i can't do a remove accounts from accounts.txt for you. I have make a results file as
- Wrong Password , error will be in ./account/result/error.txt 
- Success will be in ./account/result/success.txt
