### ISSUE TITLE
No enter after account 1 to account 2 and so on

### ISSUE THREAD

**Issue by rakage** [Holfz/de2fa#4]
Hello, after success disabling the 2fa, it save the account like:
username1:pass1:username2:pass2:username3:pass3................

How to fix that or enter each account not manually?
Thx

**Comment by Holfz** [comment]
I have created converter for you

1. npm install
2. clear password.txt and clear converted.txt
3. put username1:pass1:username2:pass2:username3:pass3........ in password.txt
4. node rakage.js
5. your converted format will be on converted.txt

[convert.zip](https://github.com/Holfz/de2fa/files/2835223/convert.zip)

**Comment by Holfz** [comment]
I will close this issues
--------

Feel free to commend this after i closed issue

**Comment by Holfz** [comment]
And here is [new version](https://github.com/Holfz/de2fa/releases/tag/v.2.0.2-v2) that fix the bug.. Thanks! for reporting the bug
